const jokes = [
  "What does a storm cloud wear under his raincoat? Thunderwear.",
  "What do kids play when their mom is using the phone? Bored games.",
  "What do you call an ant who fights crime? A vigilANTe!",
  "Why are snails slow? Because they\'re carrying a house on their back.",
  "What\'s the smartest insect? A spelling bee!",
  "What is fast, loud and crunchy? A rocket chip.",
  "How does the ocean say hi? It waves!",
  "What do you call a couple of chimpanzees sharing an Amazon account? PRIME-mates.",
  "Why did the teddy bear say no to dessert? Because she was stuffed.",
  "Why did the soccer player take so long to eat dinner? Because he thought he couldn\'t use his hands.",
  "Name the kind of tree you can hold in your hand? A palm tree!",
  "What do birds give out on Halloween? Tweets.",
  "What has ears but cannot hear? A cornfield.",
  "What\'s a cat\'s favorite dessert? A bowl full of mice-cream.",
  "Where did the music teacher leave her keys? In the piano!",
  "What did the policeman say to his hungry stomach? \"Freeze. You\'re under a vest.\"",
  "What did the left eye say to the right eye? Between us, something smells!",
  "What do you call a guy who\'s really loud? Mike.",
  "Why do birds fly south in the winter? It\'s faster than walking!",
  "What did the lava say to his girlfriend? \"I lava you!\"",
  "Why did the student eat his homework? Because the teacher told him it was a piece of cake!",
  "What did Yoda say when he saw himself in 4K? \"HDMI.\"",
  "Which superhero hits home runs? Batman!",
  "What\'s Thanos\' favorite app on his phone? Snapchat.",
  "Sandy\'s mum has four kids; North, West, East. What\'s the name of the fourth child? Sandy, obviously!",
  "What is a room with no walls? A mushroom.",
  "Why did the blue jay get in trouble at school? For tweeting on a test!",
  "What social event do spiders love to attend? Webbings.",
  "What did one volcano say to the other? I lava you.",
  "How do you get a squirrel to like you? Act like a complete nut!",
  "Why don\'t eggs tell jokes? They\'d crack each other up.",
  "What did one plate say to the other plate? Lunch is on me.",
  "Why do we never tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
  "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
  "What do you call a boomerang that won\'t come back? A stick.",
  "What did the fisherman say to the magician? Pick a cod, any cod.",
  "Why do ducks have feathers? To cover their butt quacks.",
  "What building in your town has the most stories? The public library.",
  "What loses its head in the morning and gets it back at night? A pillow.",
  "Why did the kid bring a ladder to school? Because she wanted to go to high school.",
  "What do you call an elephant that doesn\'t matter? An irrelephant.",
  "Why can\'t Elsa have a balloon? Because she will let it go.",
  "What do you call a dog magician? A labracadabrador.",
  "Where would you find an elephant? The same place you lost her!",
  "How do you stop an astronaut\'s baby from crying? You rocket.",
  "Why was 6 afraid of 7? Because 7, 8, 9.",
  "What\'s a vampire\'s favorite fruit? A blood orange.",
  "What did the cake say to the fork? You want a piece of me?",
  "What did the tree say to the wind? Leaf me alone!",
  "What\'s a tornado\'s favorite game to play? Twister.",
  "How does a cucumber become a pickle? It goes through a jarring experience.",
  "Why was the baby strawberry crying? Because her parents were in a jam.",
  "How are false teeth like stars? They come out at night!",
  "What building has the most stories? The library!",
  "What did one wall say to the other wall? I\'ll meet you at the corner.",
  "Why do bicycles fall over? Because they are two-tired!",
  "What do you call cheese that isn\'t yours? Nacho cheese.",
  "What did one snowman say to the other snowman? Do you smell carrots?",
  "What is brown, hairy and wears sunglasses? A coconut on vacation.",
  "Why did the man put his money in the freezer? He wanted cold hard cash!",
  "Why don\'t oysters donate to charity? Because they are shellfish.",
  "What do you get when you cross a vampire and a snowman? Frostbite.",
  "Why couldn\'t the pony sing? Because she was a little horse.",
  "Why don\'t skeletons fight each other? They don\'t have the guts.",
  "What did one hat say to the other? You stay here, I\'ll go on ahead.",
  "What do you call a fake noodle? An impasta.",
  "What do you call a bear with no teeth? A gummy bear.",
  "What do you call an alligator in a vest? An in-vest-igator.",
  "What do you call a sleeping bull? A bulldozer.",
  "Why don\'t scientists trust atoms? Because they make up everything.",
  "What did one toilet say to the other toilet? You look flushed.",
  "Why did the picture go to jail? Because it was framed.",
  "Why did the kid cross the playground? To get to the other slide.",
  "Why can\'t your nose be 12 inches long? Because then it would be a foot.",
  "Why was the math book sad? Because it had too many problems.",
  "Why couldn\'t the leopard play hide-and-seek? Because he was always spotted.",
  "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
  "Why did the computer go to the doctor? Because it caught a virus.",
  "Why was the broom late? It swept in.",
  "Why was the belt arrested? Because it held up a pair of pants!",
  "Why don\'t seagulls fly over the bay? Because then they\'d be bagels.",
  "Why was the calendar popular? Because it had a lot of dates.",
  "Why did the mushroom go to the party alone? Because he was a fungi.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "What did the janitor say when he jumped out of the closet? Supplies!",
  "Why did the banana go to the doctor? Because it wasn\'t peeling well.",
  "What do you call a pig that does karate? A pork chop.",
  "Why did the stadium get hot after the game? All the fans left.",
  "Why do cows wear bells? Because their horns don\'t work.",
  "Why did the bicycle fall over? Because it was two-tired.",
  "Why did the cookie go to the hospital? Because it felt crummy.",
  "Why was the computer cold? It left its Windows open.",
  "Why did the golfer bring two shirts? In case he got a hole in one.",
  "Why was the music teacher locked out of her classroom? Because her keys were on the piano.",
  "Why can\'t you give Elsa a balloon? Because she will let it go.",
  "Why was the skeleton afraid of the storm? Because he didn\'t have any guts.",
  "Why did the frog call his insurance company? He had a jump in his car.",
  "Why did the orange stop? Because it ran out of juice.",
  "Why did the man run around his bed? Because he was trying to catch up on his sleep.",
  "Why did the farmer win an award? Because he was outstanding in his field.",
  "Why did the math book look sad? Because it had too many problems.",
  "Why did the girl bring a ladder to school? Because she wanted to go to high school.",
  "Why did the boy eat his homework? Because the teacher said it was a piece of cake.",
  "Why did the chicken go to the seance? To talk to the other side.",
  "Why did the cow go to space? To see the moooon!",
  "Why did the man put his car in the oven? Because he wanted a hot rod.",
  "Why did the kid sit on his watch? Because he wanted to be on time.",
  "Why did the tomato blush? Because it saw the salad dressing.",
  "Why did the belt go to jail? For holding up a pair of pants!",
  "Why did the man bring a pencil to bed? To draw the curtains.",
  "Why did the scarecrow become a successful neurosurgeon? He was outstanding in his field.",
  "Why did the banana go out with the prune? Because it couldn\'t find a date.",
  "Why did the bicycle stand up by itself? Because it was two-tired.",
  "Why did the teacher wear sunglasses? Because her students were so bright.",
  "Why did the kid cross the playground? To get to the other slide.",
  "Why did the cat sit on the computer? To keep an eye on the mouse.",
  "Why did the skeleton cross the road? To get to the body shop.",
  "Why did the boy bring a ladder to school? Because he wanted to go to high school.",
  "Why did the grape stop in the middle of the road? Because it ran out of juice.",
  "Why did the broom get a poor grade in school? Because it was always sweeping.",
  "Why did the cookie go to the doctor? Because it felt crummy.",
  "Why did the man put his watch in the blender? He wanted to make time fly.",
  "Why did the kid throw his clock out the window? Because he wanted to see time fly.",
  "Why did the chicken go to space? To see the moooon.",
  "Why did the football coach go to the bank? To get his quarter back.",
  "Why did the cat go to medical school? To become a purr-amedic.",
  "Why did the man put his money in the blender? He wanted to make liquid assets.",
  "Why did the boy sit on the clock? He wanted to be on time.",
  "Why did the computer keep sneezing? It had a virus.",
  "Why did the duck go to the doctor? Because it was feeling a little down.",
  "Why did the man run around the bed? Because he was trying to catch up on his sleep.",
  "Why did the cow go to outer space? To see the moooon.",
  "Why did the pencil go to the party? Because it wanted to draw some attention.",
  "Why did the tomato turn red? Because it saw the salad dressing.",
  "Why did the skeleton go to the party alone? Because he had no body to go with him.",
  "Why did the boy put his shoes on his head? Because he wanted to be a head of the class.",
  "Why did the banana go to the doctor? Because it wasn\'t peeling well.",
  "Why did the dog sit in the shade? Because he didn\'t want to be a hot dog.",
  "Why did the mushroom go to the party? Because he was a fun guy.",
  "Why did the cow sit on the guitar? Because it wanted to make moo-sic.",
  "Why did the skeleton skip the dance? Because he had no body to dance with.",
  "Why did the broom get tired? Because it was sweeping all day.",
  "Why did the duck get a bad report card? Because he was always quacking jokes.",
  "Why did the horse go behind the tree? To change his jockeys.",
  "Why did the man put his radio in the refrigerator? Because he wanted to listen to cool music.",
  "Why did the cat go to the vet? Because it was feeling claw-ful.",
  "Why did the boy put his shoes on the roof? Because he wanted to have high tops.",
  "Why did the chicken join the band? Because it had the drumsticks.",
  "Why did the cow join the orchestra? Because it had the mooo-sic in it.",
  "Why did the ghost go to school? To learn how to be a better spook.",
  "Why did the banana go to the party? Because it was a-peeling.",
  "Why did the kid bring a ruler to bed? To see how long he could sleep.",
  "Why did the boy put his clock under his desk? Because he wanted to work overtime.",
  "Why did the man put his car in the blender? Because he wanted to make a smooth ride.",
  "Why did the chicken sit on the clock? Because it wanted to lay a time.",
  "Why did the cow go to music class? Because it wanted to learn how to moo-sic.",
  "Why did the skeleton go to the library? To check out a book on bones.",
  "Why did the boy put his pencil in the refrigerator? Because he wanted a cool point.",
  "Why did the dog go to the bank? To make a de-paws-it.",
  "Why did the tomato go out with the prune? Because it couldn\'t find a date.",
  "Why did the man put his computer in the oven? Because he wanted a hot byte.",
  "Why did the chicken go to the gym? To work on its pecks.",
  "Why did the cat go to school? To learn how to read purr-fectly.",
  "Why did the boy put his toy airplane in the freezer? Because he wanted a cold flight.",
  "Why did the girl put her shoes in the oven? Because she wanted warm feet.",
  "Why did the cow go to the movie theater? Because it wanted to see a moo-vie.",
  "Why did the man put his phone in the blender? Because he wanted to make a smoothie call.",
  "Why did the skeleton go to the dance? Because he had no body to dance with.",
  "Why did the chicken go to the library? To check out a book on eggs.",
  "Why did the cat sit on the computer? To keep an eye on the mouse.",
  "Why did the dog go to the party? Because he was a party animal.",
  "Why did the boy put his watch in the refrigerator? Because he wanted cold time.",
  "Why did the girl put her bicycle in the freezer? Because she wanted a cool ride.",
  "Why did the chicken go to school? To learn how to be egg-cellent.",
  "Why did the cow go to the circus? To see the moo-icians.",
  "Why did the skeleton go to the store? To buy some spare ribs.",
  "Why did the cat go to the dentist? Because it had a bad tooth.",
  "Why did the boy put his shoes in the refrigerator? Because he wanted cold feet.",
  "Why did the girl put her clock in the oven? Because she wanted hot time.",
  "Why did the chicken go to the playground? To play on the jungle gym.",
  "Why did the cow go to the amusement park? To ride the roller mooo-ster.",
  "Why did the skeleton go to the bar? To get a beer.",
  "Why did the cat go to the doctor? Because it was feeling claw-ful.",
  "Why did the dog go to the beach? To play in the sand.",
  "Why did the boy put his clock in the freezer? Because he wanted cold time.",
  "Why did the girl put her shoes in the refrigerator? Because she wanted cold feet.",
  "Why did the chicken go to the farm? To see the moo-cows.",
  "Why did the cow go to the zoo? To see the other animals.",
  "Why did the skeleton go to the gym? To work on his bones.",
  "Why did the cat go to the park? To play on the swings.",
  "Why did the dog go to the park? To chase the squirrels.",
  "Why did the boy put his watch in the oven? Because he wanted hot time.",
  "Why did the girl put her bicycle in the refrigerator? Because she wanted a cool ride.",
  "Why did the chicken go to the store? To buy some eggs.",
  "Why did the cow go to the restaurant? To eat some grass.",
  "Why did the skeleton go to the beach? To get a tan.",
  "Why did the cat go to the library? To check out a book on mice.",
  "Why did the dog go to the vet? Because it was feeling ruff.",
  "Why did the boy put his shoes in the oven? Because he wanted hot feet.",
  "Why did the girl put her clock in the refrigerator? Because she wanted cold time.",
  "Why did the chicken go to the park? To play on the swings.",
  "Why did the cow go to the mall? To go shopping.",
  "Why did the skeleton go to the doctor? To get a checkup.",
  "Why did the cat go to the pet store? To buy some fish.",
  "Why did the dog go to the groomer? To get a haircut.",
  "Why did the boy put his watch in the refrigerator? Because he wanted cold time.",
  "Why did the girl put her bicycle in the oven? Because she wanted a hot ride.",
  "Why did the chicken go to the zoo? To see the lions.",
  "Why did the cow go to the theater? To see a play.",
  "Why did the skeleton go to the party? Because he had no body to go with him.",
  "Why did the cat go to the park? To play on the swings.",
  "Why did the dog go to the park? To chase the squirrels.",
  "Why did the boy put his shoes in the refrigerator? Because he wanted cold feet.",
  "Why did the girl put her clock in the oven? Because she wanted hot time.",
  "Why did the chicken go to the playground? To play on the swings.",
  "Why did the cow go to the amusement park? To ride the roller coaster.",
  "Why did the skeleton go to the bar? To get a beer.",
  "Why did the cat go to the doctor? Because it was feeling claw-ful.",
  "Why did the dog go to the beach? To play in the sand."
];
// console.log(jokes.length);
let r = Math.floor((Math.random()*219));
const j = document.getElementById("joke");
j.innerHTML= jokes[r];
